curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/1.png -o ./thumb/1.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/1.png -o ./detail/1.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/2.png -o ./thumb/2.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/2.png -o ./detail/2.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/3.png -o ./thumb/3.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/3.png -o ./detail/3.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/4.png -o ./thumb/4.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/4.png -o ./detail/4.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/5.png -o ./thumb/5.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/5.png -o ./detail/5.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/6.png -o ./thumb/6.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/6.png -o ./detail/6.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/7.png -o ./thumb/7.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/7.png -o ./detail/7.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/8.png -o ./thumb/8.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/8.png -o ./detail/8.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/9.png -o ./thumb/9.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/9.png -o ./detail/9.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/10.png -o ./thumb/10.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/10.png -o ./detail/10.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/11.png -o ./thumb/11.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/11.png -o ./detail/11.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/12.png -o ./thumb/12.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/12.png -o ./detail/12.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/13.png -o ./thumb/13.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/13.png -o ./detail/13.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/14.png -o ./thumb/14.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/14.png -o ./detail/14.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/15.png -o ./thumb/15.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/15.png -o ./detail/15.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/16.png -o ./thumb/16.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/16.png -o ./detail/16.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/17.png -o ./thumb/17.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/17.png -o ./detail/17.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/18.png -o ./thumb/18.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/18.png -o ./detail/18.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/19.png -o ./thumb/19.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/19.png -o ./detail/19.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/20.png -o ./thumb/20.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/20.png -o ./detail/20.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/21.png -o ./thumb/21.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/21.png -o ./detail/21.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/22.png -o ./thumb/22.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/22.png -o ./detail/22.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/23.png -o ./thumb/23.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/23.png -o ./detail/23.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/24.png -o ./thumb/24.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/24.png -o ./detail/24.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/25.png -o ./thumb/25.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/25.png -o ./detail/25.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/26.png -o ./thumb/26.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/26.png -o ./detail/26.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/27.png -o ./thumb/27.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/27.png -o ./detail/27.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/28.png -o ./thumb/28.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/28.png -o ./detail/28.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/29.png -o ./thumb/29.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/29.png -o ./detail/29.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/30.png -o ./thumb/30.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/30.png -o ./detail/30.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/31.png -o ./thumb/31.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/31.png -o ./detail/31.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/32.png -o ./thumb/32.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/32.png -o ./detail/32.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/33.png -o ./thumb/33.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/33.png -o ./detail/33.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/34.png -o ./thumb/34.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/34.png -o ./detail/34.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/35.png -o ./thumb/35.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/35.png -o ./detail/35.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/36.png -o ./thumb/36.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/36.png -o ./detail/36.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/37.png -o ./thumb/37.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/37.png -o ./detail/37.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/38.png -o ./thumb/38.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/38.png -o ./detail/38.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/39.png -o ./thumb/39.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/39.png -o ./detail/39.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/40.png -o ./thumb/40.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/40.png -o ./detail/40.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/41.png -o ./thumb/41.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/41.png -o ./detail/41.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/42.png -o ./thumb/42.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/42.png -o ./detail/42.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/43.png -o ./thumb/43.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/43.png -o ./detail/43.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/44.png -o ./thumb/44.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/44.png -o ./detail/44.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/45.png -o ./thumb/45.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/45.png -o ./detail/45.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/46.png -o ./thumb/46.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/46.png -o ./detail/46.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/47.png -o ./thumb/47.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/47.png -o ./detail/47.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/48.png -o ./thumb/48.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/48.png -o ./detail/48.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/49.png -o ./thumb/49.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/49.png -o ./detail/49.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/50.png -o ./thumb/50.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/50.png -o ./detail/50.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/51.png -o ./thumb/51.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/51.png -o ./detail/51.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/52.png -o ./thumb/52.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/52.png -o ./detail/52.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/53.png -o ./thumb/53.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/53.png -o ./detail/53.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/54.png -o ./thumb/54.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/54.png -o ./detail/54.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/55.png -o ./thumb/55.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/55.png -o ./detail/55.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/56.png -o ./thumb/56.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/56.png -o ./detail/56.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/57.png -o ./thumb/57.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/57.png -o ./detail/57.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/58.png -o ./thumb/58.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/58.png -o ./detail/58.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/59.png -o ./thumb/59.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/59.png -o ./detail/59.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/60.png -o ./thumb/60.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/60.png -o ./detail/60.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/61.png -o ./thumb/61.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/61.png -o ./detail/61.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/62.png -o ./thumb/62.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/62.png -o ./detail/62.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/63.png -o ./thumb/63.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/63.png -o ./detail/63.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/64.png -o ./thumb/64.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/64.png -o ./detail/64.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/65.png -o ./thumb/65.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/65.png -o ./detail/65.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/66.png -o ./thumb/66.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/66.png -o ./detail/66.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/67.png -o ./thumb/67.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/67.png -o ./detail/67.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/68.png -o ./thumb/68.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/68.png -o ./detail/68.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/69.png -o ./thumb/69.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/69.png -o ./detail/69.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/70.png -o ./thumb/70.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/70.png -o ./detail/70.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/71.png -o ./thumb/71.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/71.png -o ./detail/71.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/72.png -o ./thumb/72.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/72.png -o ./detail/72.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/73.png -o ./thumb/73.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/73.png -o ./detail/73.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/74.png -o ./thumb/74.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/74.png -o ./detail/74.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/75.png -o ./thumb/75.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/75.png -o ./detail/75.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/76.png -o ./thumb/76.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/76.png -o ./detail/76.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/77.png -o ./thumb/77.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/77.png -o ./detail/77.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/78.png -o ./thumb/78.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/78.png -o ./detail/78.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/79.png -o ./thumb/79.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/79.png -o ./detail/79.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/80.png -o ./thumb/80.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/80.png -o ./detail/80.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/81.png -o ./thumb/81.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/81.png -o ./detail/81.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/82.png -o ./thumb/82.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/82.png -o ./detail/82.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/83.png -o ./thumb/83.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/83.png -o ./detail/83.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/84.png -o ./thumb/84.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/84.png -o ./detail/84.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/85.png -o ./thumb/85.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/85.png -o ./detail/85.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/86.png -o ./thumb/86.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/86.png -o ./detail/86.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/87.png -o ./thumb/87.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/87.png -o ./detail/87.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/88.png -o ./thumb/88.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/88.png -o ./detail/88.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/89.png -o ./thumb/89.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/89.png -o ./detail/89.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/90.png -o ./thumb/90.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/90.png -o ./detail/90.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/91.png -o ./thumb/91.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/91.png -o ./detail/91.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/92.png -o ./thumb/92.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/92.png -o ./detail/92.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/93.png -o ./thumb/93.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/93.png -o ./detail/93.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/94.png -o ./thumb/94.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/94.png -o ./detail/94.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/95.png -o ./thumb/95.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/95.png -o ./detail/95.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/96.png -o ./thumb/96.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/96.png -o ./detail/96.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/97.png -o ./thumb/97.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/97.png -o ./detail/97.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/98.png -o ./thumb/98.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/98.png -o ./detail/98.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/99.png -o ./thumb/99.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/99.png -o ./detail/99.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/100.png -o ./thumb/100.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/100.png -o ./detail/100.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/101.png -o ./thumb/101.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/101.png -o ./detail/101.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/102.png -o ./thumb/102.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/102.png -o ./detail/102.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/103.png -o ./thumb/103.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/103.png -o ./detail/103.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/104.png -o ./thumb/104.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/104.png -o ./detail/104.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/105.png -o ./thumb/105.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/105.png -o ./detail/105.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/106.png -o ./thumb/106.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/106.png -o ./detail/106.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/107.png -o ./thumb/107.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/107.png -o ./detail/107.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/108.png -o ./thumb/108.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/108.png -o ./detail/108.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/109.png -o ./thumb/109.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/109.png -o ./detail/109.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/110.png -o ./thumb/110.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/110.png -o ./detail/110.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/111.png -o ./thumb/111.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/111.png -o ./detail/111.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/112.png -o ./thumb/112.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/112.png -o ./detail/112.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/113.png -o ./thumb/113.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/113.png -o ./detail/113.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/114.png -o ./thumb/114.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/114.png -o ./detail/114.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/115.png -o ./thumb/115.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/115.png -o ./detail/115.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/116.png -o ./thumb/116.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/116.png -o ./detail/116.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/117.png -o ./thumb/117.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/117.png -o ./detail/117.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/118.png -o ./thumb/118.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/118.png -o ./detail/118.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/119.png -o ./thumb/119.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/119.png -o ./detail/119.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/120.png -o ./thumb/120.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/120.png -o ./detail/120.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/121.png -o ./thumb/121.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/121.png -o ./detail/121.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/122.png -o ./thumb/122.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/122.png -o ./detail/122.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/123.png -o ./thumb/123.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/123.png -o ./detail/123.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/124.png -o ./thumb/124.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/124.png -o ./detail/124.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/125.png -o ./thumb/125.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/125.png -o ./detail/125.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/126.png -o ./thumb/126.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/126.png -o ./detail/126.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/127.png -o ./thumb/127.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/127.png -o ./detail/127.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/128.png -o ./thumb/128.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/128.png -o ./detail/128.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/129.png -o ./thumb/129.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/129.png -o ./detail/129.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/130.png -o ./thumb/130.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/130.png -o ./detail/130.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/131.png -o ./thumb/131.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/131.png -o ./detail/131.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/132.png -o ./thumb/132.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/132.png -o ./detail/132.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/133.png -o ./thumb/133.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/133.png -o ./detail/133.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/134.png -o ./thumb/134.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/134.png -o ./detail/134.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/135.png -o ./thumb/135.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/135.png -o ./detail/135.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/136.png -o ./thumb/136.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/136.png -o ./detail/136.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/137.png -o ./thumb/137.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/137.png -o ./detail/137.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/138.png -o ./thumb/138.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/138.png -o ./detail/138.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/139.png -o ./thumb/139.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/139.png -o ./detail/139.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/140.png -o ./thumb/140.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/140.png -o ./detail/140.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/141.png -o ./thumb/141.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/141.png -o ./detail/141.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/142.png -o ./thumb/142.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/142.png -o ./detail/142.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/143.png -o ./thumb/143.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/143.png -o ./detail/143.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/144.png -o ./thumb/144.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/144.png -o ./detail/144.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/145.png -o ./thumb/145.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/145.png -o ./detail/145.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/146.png -o ./thumb/146.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/146.png -o ./detail/146.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/147.png -o ./thumb/147.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/147.png -o ./detail/147.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/148.png -o ./thumb/148.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/148.png -o ./detail/148.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/149.png -o ./thumb/149.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/149.png -o ./detail/149.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/150.png -o ./thumb/150.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/150.png -o ./detail/150.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/151.png -o ./thumb/151.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/151.png -o ./detail/151.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/152.png -o ./thumb/152.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/152.png -o ./detail/152.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/153.png -o ./thumb/153.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/153.png -o ./detail/153.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/154.png -o ./thumb/154.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/154.png -o ./detail/154.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/155.png -o ./thumb/155.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/155.png -o ./detail/155.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/156.png -o ./thumb/156.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/156.png -o ./detail/156.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/157.png -o ./thumb/157.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/157.png -o ./detail/157.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/158.png -o ./thumb/158.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/158.png -o ./detail/158.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/159.png -o ./thumb/159.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/159.png -o ./detail/159.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/160.png -o ./thumb/160.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/160.png -o ./detail/160.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/161.png -o ./thumb/161.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/161.png -o ./detail/161.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/162.png -o ./thumb/162.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/162.png -o ./detail/162.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/163.png -o ./thumb/163.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/163.png -o ./detail/163.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/164.png -o ./thumb/164.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/164.png -o ./detail/164.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/165.png -o ./thumb/165.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/165.png -o ./detail/165.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/166.png -o ./thumb/166.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/166.png -o ./detail/166.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/167.png -o ./thumb/167.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/167.png -o ./detail/167.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/168.png -o ./thumb/168.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/168.png -o ./detail/168.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/169.png -o ./thumb/169.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/169.png -o ./detail/169.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/170.png -o ./thumb/170.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/170.png -o ./detail/170.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/171.png -o ./thumb/171.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/171.png -o ./detail/171.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/172.png -o ./thumb/172.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/172.png -o ./detail/172.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/173.png -o ./thumb/173.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/173.png -o ./detail/173.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/174.png -o ./thumb/174.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/174.png -o ./detail/174.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/175.png -o ./thumb/175.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/175.png -o ./detail/175.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/176.png -o ./thumb/176.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/176.png -o ./detail/176.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/177.png -o ./thumb/177.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/177.png -o ./detail/177.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/178.png -o ./thumb/178.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/178.png -o ./detail/178.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/179.png -o ./thumb/179.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/179.png -o ./detail/179.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/180.png -o ./thumb/180.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/180.png -o ./detail/180.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/181.png -o ./thumb/181.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/181.png -o ./detail/181.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/182.png -o ./thumb/182.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/182.png -o ./detail/182.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/183.png -o ./thumb/183.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/183.png -o ./detail/183.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/184.png -o ./thumb/184.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/184.png -o ./detail/184.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/185.png -o ./thumb/185.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/185.png -o ./detail/185.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/186.png -o ./thumb/186.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/186.png -o ./detail/186.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/187.png -o ./thumb/187.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/187.png -o ./detail/187.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/188.png -o ./thumb/188.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/188.png -o ./detail/188.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/189.png -o ./thumb/189.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/189.png -o ./detail/189.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/190.png -o ./thumb/190.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/190.png -o ./detail/190.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/191.png -o ./thumb/191.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/191.png -o ./detail/191.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/192.png -o ./thumb/192.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/192.png -o ./detail/192.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/193.png -o ./thumb/193.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/193.png -o ./detail/193.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/194.png -o ./thumb/194.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/194.png -o ./detail/194.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/195.png -o ./thumb/195.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/195.png -o ./detail/195.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/196.png -o ./thumb/196.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/196.png -o ./detail/196.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/197.png -o ./thumb/197.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/197.png -o ./detail/197.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/198.png -o ./thumb/198.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/198.png -o ./detail/198.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/199.png -o ./thumb/199.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/199.png -o ./detail/199.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/200.png -o ./thumb/200.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/200.png -o ./detail/200.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/201.png -o ./thumb/201.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/201.png -o ./detail/201.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/202.png -o ./thumb/202.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/202.png -o ./detail/202.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/203.png -o ./thumb/203.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/203.png -o ./detail/203.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/204.png -o ./thumb/204.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/204.png -o ./detail/204.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/205.png -o ./thumb/205.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/205.png -o ./detail/205.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/206.png -o ./thumb/206.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/206.png -o ./detail/206.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/207.png -o ./thumb/207.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/207.png -o ./detail/207.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/208.png -o ./thumb/208.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/208.png -o ./detail/208.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/209.png -o ./thumb/209.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/209.png -o ./detail/209.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/210.png -o ./thumb/210.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/210.png -o ./detail/210.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/211.png -o ./thumb/211.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/211.png -o ./detail/211.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/212.png -o ./thumb/212.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/212.png -o ./detail/212.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/213.png -o ./thumb/213.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/213.png -o ./detail/213.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/214.png -o ./thumb/214.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/214.png -o ./detail/214.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/215.png -o ./thumb/215.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/215.png -o ./detail/215.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/216.png -o ./thumb/216.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/216.png -o ./detail/216.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/217.png -o ./thumb/217.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/217.png -o ./detail/217.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/218.png -o ./thumb/218.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/218.png -o ./detail/218.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/219.png -o ./thumb/219.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/219.png -o ./detail/219.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/220.png -o ./thumb/220.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/220.png -o ./detail/220.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/221.png -o ./thumb/221.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/221.png -o ./detail/221.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/222.png -o ./thumb/222.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/222.png -o ./detail/222.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/223.png -o ./thumb/223.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/223.png -o ./detail/223.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/224.png -o ./thumb/224.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/224.png -o ./detail/224.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/225.png -o ./thumb/225.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/225.png -o ./detail/225.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/226.png -o ./thumb/226.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/226.png -o ./detail/226.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/227.png -o ./thumb/227.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/227.png -o ./detail/227.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/228.png -o ./thumb/228.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/228.png -o ./detail/228.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/thumb/229.png -o ./thumb/229.png &&
curl https://c.cid.capcom.com/rsrc/mh20th-vote/assets/img/detail/229.png -o ./detail/229.png